### ISSUE TITLE
Floor Generator & Blender 2.80/2.81 compatibility 

### ISSUE THREAD

**Issue by xan2622** [varkenvarken/blenderaddons#10]
Hi.

Could it be possible to update Floor Generator, to make it compatible with Blender 2.80/2.81 ?
Thank you

**Comment by powlly** [comment]
Yes that is a good question.

**Comment by varkenvarken** [comment]
I'll have a look. No promises yet on the timeline but it shouldn't be too difficult ;-)

**Comment by varkenvarken** [comment]
just updated it. Mind, this is a straight port and nothing more, i.e. everything works and I get no errors but this add-on shows its age and is in need of some serious attention. For example, the generated mesh is not always looking great when shaded, even with the bevel modifier on it and all the persistent options are at the object level (no property group) which is a bad practice (but will break backward compatibility if changed).  Anyway, for now it seems to work, enjoy :-)
