### ISSUE TITLE
WeightToVertexColor

### ISSUE THREAD

**Issue by ludogemma** [varkenvarken/blenderaddons#13]
Hi there i tried your addon on 2.83 (don't install) and 2.9x (install correctly)

in paint menu there's 2 options:

https://prnt.sc/uuysdd

vertex color from weights works 

but the weightToVertexColor return error:
https://prnt.sc/uuyuar

in Weight paint menu
there's only VertexColorTowWeight but is always greyed out and can't use.

thank you

**Comment by varkenvarken** [comment]
I'll have a look this weekend, thanks for bringing it to my attention

**Comment by varkenvarken** [comment]
Hi,

I realized that the first menu entry (Vertex Color from Weight) is actually a new **built-in** Blender operator. It will be greyed out if there is no vertex group or when there are no vertices assigned to that vertex group.

This makes my add-on superfluous I think, so I will mark this issue as 'wont fix' unless there is a good reason to keep it around.

**Comment by ludogemma** [comment]
ok but maybe i didn't explain right the issue.. i have my mesh with assigned vertex group (weights) in fact i can use the "vertex color from weight) built-in blender and works (your menu entry "WeightToVertexColor"
https://prnt.sc/uwbwrm
gives this error:
https://prnt.sc/uwbxvx
but it's not true the vertex are assigned in groups..

and the other menu also "VertexColorToWeight" is greyed out but theres' vertex painted and also weight groups.
https://prnt.sc/uwbyre

so maybe something is wrong in the addon..
if you tell me in your weight lifter addon all works.. i will purchase that

thanks

**Comment by varkenvarken** [comment]
Ok I will have another look then (and yes WeightLifter is tested with 2.83 but i will try to fix these free add-ons as well :-)

**Comment by varkenvarken** [comment]
fixed both issues and cleaned up the code a bit. Please have a try.

**Comment by ludogemma** [comment]
Hi thanks.. but still there's not a menu entry to VERTEX COLOR TO WEIGHT...  only weight from vertex color..

https://prnt.sc/ux7g6p

and in WEIGHT paint there's no menu entry .
https://prnt.sc/ux7gl3

**Comment by ludogemma** [comment]
now works perfectly!!
thank you very much :)
