### ISSUE TITLE
randomvertexcolor280 doesn't support multi-object selections

### ISSUE THREAD

**Issue by eobet** [varkenvarken/blenderaddons#15]
When I try to select all objects (or all objects by type) and go into vertex paint mode, I get the following error:

![image](https://user-images.githubusercontent.com/3254196/141650958-f77f381c-ba92-44f5-8953-26f565fd770a.png)

You're probably not updating this, and it's probably a pain to filter out for example instances, but thought I'd raise the issue and see what happens. 🙂

**Comment by varkenvarken** [comment]
I believe this was not related to the selection of multiple objects but to changes in the Python API (particularly moving the update() method from Scene to View layer. But I have updated it and it seems to work fine in my 2.93.4 LTS :-)
