### ISSUE TITLE
ColorRamp picker doesn't work in compositor nodes

### ISSUE THREAD

**Issue by gabrielmontagne** [varkenvarken/blenderaddons#7]
The option is only enabled for shader `ColorRamp` nodes; I wanted to use it on the compositor node tree as well -- is there a fundamental reason why it should be disabled for this node tree type?

**Comment by varkenvarken** [comment]
Hi Gabriel,

i don't think there actually is a technical restriction. I will have a look next week

**Comment by gabrielmontagne** [comment]
Thanks!

**Comment by varkenvarken** [comment]
colorramppicker.py should now work for compositor colorramps as well (theoretically any colorramp node).
(note that I renamed the file)

**Comment by gabrielmontagne** [comment]
it absolutely works! thanks so much.
